/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as OurDayRouteImport } from './routes/our-day'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as SongRouteImport } from './routes/song'
import { Route as StoryRouteImport } from './routes/story'
import { Route as VideoRouteImport } from './routes/video'
import { Route as WhyRouteImport } from './routes/why'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const OurDayRoute = OurDayRouteImport.update({
  id: '/our-day',
  path: '/our-day',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const SongRoute = SongRouteImport.update({
  id: '/song',
  path: '/song',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/our-day': typeof OurDayRoute
  '/secret': typeof SecretRoute
  '/song': typeof SongRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/our-day': typeof OurDayRoute
  '/secret': typeof SecretRoute
  '/song': typeof SongRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/our-day': typeof OurDayRoute
  '/secret': typeof SecretRoute
  '/song': typeof SongRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/why': typeof WhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/letter'
    | '/memories'
    | '/our-day'
    | '/secret'
    | '/song'
    | '/story'
    | '/video'
    | '/why'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/letter'
    | '/memories'
    | '/our-day'
    | '/secret'
    | '/song'
    | '/story'
    | '/video'
    | '/why'
  id:
    | '__root__'
    | '/'
    | '/letter'
    | '/memories'
    | '/our-day'
    | '/secret'
    | '/song'
    | '/story'
    | '/video'
    | '/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LetterRoute: typeof LetterRoute
  MemoriesRoute: typeof MemoriesRoute
  OurDayRoute: typeof OurDayRoute
  SecretRoute: typeof SecretRoute
  SongRoute: typeof SongRoute
  StoryRoute: typeof StoryRoute
  VideoRoute: typeof VideoRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-day': {
      id: '/our-day'
      path: '/our-day'
      fullPath: '/our-day'
      preLoaderRoute: typeof OurDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song': {
      id: '/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof SongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LetterRoute: LetterRoute,
  MemoriesRoute: MemoriesRoute,
  OurDayRoute: OurDayRoute,
  SecretRoute: SecretRoute,
  SongRoute: SongRoute,
  StoryRoute: StoryRoute,
  VideoRoute: VideoRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
